name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        node-version: [18.x]
    env:
      VERSION: ${{github.sha}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      
      - name: Setup Yarn
        run: npm install -g yarn

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          cd frontend
          yarn install
    
      - name: Build by Pyinstaller
        run: |
          cd backend
          pyinstaller -F main.py -n entropy_search_backend

      - name: Build Frontend
        run: |
          cd frontend
          yarn run dist
          ls -l dist

    #   - name: Rename electron release
    #     run: |
    #       cd frontend
    #       mv dist/entropy_search_frontend-0.1.0.dmg dist/entropy_search_frontend.dmg
    #       mv dist/entropy_search_frontend-0.1.0.AppImage dist/entropy_search_frontend.AppImage
    #       mv dist/entropy_search_frontend-0.1.0.exe dist/entropy_search_frontend.exe
    #       mv dist/entropy_search_frontend-0.1.0.tar.gz dist/entropy_search_frontend.tar.gz

      - name: Deploy to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            frontend/dist/EntropySearch*
          tag_name: ${{github.sha}}
          body: ${{github.event.inputs.body}}
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}