name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          cd frontend
          npm install
    
      - name: Build by Pyinstaller
        run: |
          cd backend
          pyinstaller -F main.py -n entropy_search_backend

      - name: Build Frontend
        run: |
          cd frontend
          npm run dist

      - name: Deploy to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            frontend/dist
          tag_name: ${{github.sha}}
          body: ${{github.event.inputs.body}}
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}